package management.actionManagement.actions;

public enum ActionType {
    //Turn events:
    BEFORE_DEAL_DAMAGE, DURING_DEAL_DAMAGE, AFTER_DEAL_DAMAGE
    , BEFORE_HEALING, DURING_HEALING, AFTER_HEALING
    , BEFORE_ATTACK, DURING_ATTACK, AFTER_ATTACK
    , BEFORE_TREATMENT, DURING_TREATMENT, AFTER_TREATMENT
    , BEFORE_USED_POSSIBILITY, DURING_USING_POSSIBILITY, AFTER_USED_POSSIBILITY
    , BEFORE_USED_SKILL, DURING_USING_SKILL, AFTER_USED_SKILL
    , BEFORE_USED_SWAP_ABILITY, DURING_USING_SWAP_ABILITY, AFTER_USED_SWAP_ABILITY
    , BEFORE_USED_BONUS, DURING_USING_BONUS, AFTER_USED_BONUS
    , BEFORE_GETTING_EXPERIENCE, DURING_GETTING_EXPERIENCE, AFTER_GETTING_EXPERIENCE
    , SWAP_HEROES

    //Main events:
    , START_TURN, END_TURN, SKIP_TURN
    , SHOWED_BONUSES, PLAYER_OUT, END_GAME
    , GET_TIME_FRAME
}